# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/william/Develop/invaders

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/william/Develop/invaders

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/william/Develop/invaders/CMakeFiles /home/william/Develop/invaders/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/william/Develop/invaders/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named invaders

# Build rule for target.
invaders: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 invaders
.PHONY : invaders

# fast build rule for target.
invaders/fast:
	$(MAKE) -f CMakeFiles/invaders.dir/build.make CMakeFiles/invaders.dir/build
.PHONY : invaders/fast

src/CFont.o: src/CFont.cpp.o
.PHONY : src/CFont.o

# target to build an object file
src/CFont.cpp.o:
	$(MAKE) -f CMakeFiles/invaders.dir/build.make CMakeFiles/invaders.dir/src/CFont.cpp.o
.PHONY : src/CFont.cpp.o

src/CFont.i: src/CFont.cpp.i
.PHONY : src/CFont.i

# target to preprocess a source file
src/CFont.cpp.i:
	$(MAKE) -f CMakeFiles/invaders.dir/build.make CMakeFiles/invaders.dir/src/CFont.cpp.i
.PHONY : src/CFont.cpp.i

src/CFont.s: src/CFont.cpp.s
.PHONY : src/CFont.s

# target to generate assembly for a file
src/CFont.cpp.s:
	$(MAKE) -f CMakeFiles/invaders.dir/build.make CMakeFiles/invaders.dir/src/CFont.cpp.s
.PHONY : src/CFont.cpp.s

src/CGame.o: src/CGame.cpp.o
.PHONY : src/CGame.o

# target to build an object file
src/CGame.cpp.o:
	$(MAKE) -f CMakeFiles/invaders.dir/build.make CMakeFiles/invaders.dir/src/CGame.cpp.o
.PHONY : src/CGame.cpp.o

src/CGame.i: src/CGame.cpp.i
.PHONY : src/CGame.i

# target to preprocess a source file
src/CGame.cpp.i:
	$(MAKE) -f CMakeFiles/invaders.dir/build.make CMakeFiles/invaders.dir/src/CGame.cpp.i
.PHONY : src/CGame.cpp.i

src/CGame.s: src/CGame.cpp.s
.PHONY : src/CGame.s

# target to generate assembly for a file
src/CGame.cpp.s:
	$(MAKE) -f CMakeFiles/invaders.dir/build.make CMakeFiles/invaders.dir/src/CGame.cpp.s
.PHONY : src/CGame.cpp.s

src/CImage.o: src/CImage.cpp.o
.PHONY : src/CImage.o

# target to build an object file
src/CImage.cpp.o:
	$(MAKE) -f CMakeFiles/invaders.dir/build.make CMakeFiles/invaders.dir/src/CImage.cpp.o
.PHONY : src/CImage.cpp.o

src/CImage.i: src/CImage.cpp.i
.PHONY : src/CImage.i

# target to preprocess a source file
src/CImage.cpp.i:
	$(MAKE) -f CMakeFiles/invaders.dir/build.make CMakeFiles/invaders.dir/src/CImage.cpp.i
.PHONY : src/CImage.cpp.i

src/CImage.s: src/CImage.cpp.s
.PHONY : src/CImage.s

# target to generate assembly for a file
src/CImage.cpp.s:
	$(MAKE) -f CMakeFiles/invaders.dir/build.make CMakeFiles/invaders.dir/src/CImage.cpp.s
.PHONY : src/CImage.cpp.s

src/CMultiImage.o: src/CMultiImage.cpp.o
.PHONY : src/CMultiImage.o

# target to build an object file
src/CMultiImage.cpp.o:
	$(MAKE) -f CMakeFiles/invaders.dir/build.make CMakeFiles/invaders.dir/src/CMultiImage.cpp.o
.PHONY : src/CMultiImage.cpp.o

src/CMultiImage.i: src/CMultiImage.cpp.i
.PHONY : src/CMultiImage.i

# target to preprocess a source file
src/CMultiImage.cpp.i:
	$(MAKE) -f CMakeFiles/invaders.dir/build.make CMakeFiles/invaders.dir/src/CMultiImage.cpp.i
.PHONY : src/CMultiImage.cpp.i

src/CMultiImage.s: src/CMultiImage.cpp.s
.PHONY : src/CMultiImage.s

# target to generate assembly for a file
src/CMultiImage.cpp.s:
	$(MAKE) -f CMakeFiles/invaders.dir/build.make CMakeFiles/invaders.dir/src/CMultiImage.cpp.s
.PHONY : src/CMultiImage.cpp.s

src/CSound.o: src/CSound.cpp.o
.PHONY : src/CSound.o

# target to build an object file
src/CSound.cpp.o:
	$(MAKE) -f CMakeFiles/invaders.dir/build.make CMakeFiles/invaders.dir/src/CSound.cpp.o
.PHONY : src/CSound.cpp.o

src/CSound.i: src/CSound.cpp.i
.PHONY : src/CSound.i

# target to preprocess a source file
src/CSound.cpp.i:
	$(MAKE) -f CMakeFiles/invaders.dir/build.make CMakeFiles/invaders.dir/src/CSound.cpp.i
.PHONY : src/CSound.cpp.i

src/CSound.s: src/CSound.cpp.s
.PHONY : src/CSound.s

# target to generate assembly for a file
src/CSound.cpp.s:
	$(MAKE) -f CMakeFiles/invaders.dir/build.make CMakeFiles/invaders.dir/src/CSound.cpp.s
.PHONY : src/CSound.cpp.s

src/CSprite.o: src/CSprite.cpp.o
.PHONY : src/CSprite.o

# target to build an object file
src/CSprite.cpp.o:
	$(MAKE) -f CMakeFiles/invaders.dir/build.make CMakeFiles/invaders.dir/src/CSprite.cpp.o
.PHONY : src/CSprite.cpp.o

src/CSprite.i: src/CSprite.cpp.i
.PHONY : src/CSprite.i

# target to preprocess a source file
src/CSprite.cpp.i:
	$(MAKE) -f CMakeFiles/invaders.dir/build.make CMakeFiles/invaders.dir/src/CSprite.cpp.i
.PHONY : src/CSprite.cpp.i

src/CSprite.s: src/CSprite.cpp.s
.PHONY : src/CSprite.s

# target to generate assembly for a file
src/CSprite.cpp.s:
	$(MAKE) -f CMakeFiles/invaders.dir/build.make CMakeFiles/invaders.dir/src/CSprite.cpp.s
.PHONY : src/CSprite.cpp.s

src/MenuState.o: src/MenuState.cpp.o
.PHONY : src/MenuState.o

# target to build an object file
src/MenuState.cpp.o:
	$(MAKE) -f CMakeFiles/invaders.dir/build.make CMakeFiles/invaders.dir/src/MenuState.cpp.o
.PHONY : src/MenuState.cpp.o

src/MenuState.i: src/MenuState.cpp.i
.PHONY : src/MenuState.i

# target to preprocess a source file
src/MenuState.cpp.i:
	$(MAKE) -f CMakeFiles/invaders.dir/build.make CMakeFiles/invaders.dir/src/MenuState.cpp.i
.PHONY : src/MenuState.cpp.i

src/MenuState.s: src/MenuState.cpp.s
.PHONY : src/MenuState.s

# target to generate assembly for a file
src/MenuState.cpp.s:
	$(MAKE) -f CMakeFiles/invaders.dir/build.make CMakeFiles/invaders.dir/src/MenuState.cpp.s
.PHONY : src/MenuState.cpp.s

src/PauseState.o: src/PauseState.cpp.o
.PHONY : src/PauseState.o

# target to build an object file
src/PauseState.cpp.o:
	$(MAKE) -f CMakeFiles/invaders.dir/build.make CMakeFiles/invaders.dir/src/PauseState.cpp.o
.PHONY : src/PauseState.cpp.o

src/PauseState.i: src/PauseState.cpp.i
.PHONY : src/PauseState.i

# target to preprocess a source file
src/PauseState.cpp.i:
	$(MAKE) -f CMakeFiles/invaders.dir/build.make CMakeFiles/invaders.dir/src/PauseState.cpp.i
.PHONY : src/PauseState.cpp.i

src/PauseState.s: src/PauseState.cpp.s
.PHONY : src/PauseState.s

# target to generate assembly for a file
src/PauseState.cpp.s:
	$(MAKE) -f CMakeFiles/invaders.dir/build.make CMakeFiles/invaders.dir/src/PauseState.cpp.s
.PHONY : src/PauseState.cpp.s

src/PlayState.o: src/PlayState.cpp.o
.PHONY : src/PlayState.o

# target to build an object file
src/PlayState.cpp.o:
	$(MAKE) -f CMakeFiles/invaders.dir/build.make CMakeFiles/invaders.dir/src/PlayState.cpp.o
.PHONY : src/PlayState.cpp.o

src/PlayState.i: src/PlayState.cpp.i
.PHONY : src/PlayState.i

# target to preprocess a source file
src/PlayState.cpp.i:
	$(MAKE) -f CMakeFiles/invaders.dir/build.make CMakeFiles/invaders.dir/src/PlayState.cpp.i
.PHONY : src/PlayState.cpp.i

src/PlayState.s: src/PlayState.cpp.s
.PHONY : src/PlayState.s

# target to generate assembly for a file
src/PlayState.cpp.s:
	$(MAKE) -f CMakeFiles/invaders.dir/build.make CMakeFiles/invaders.dir/src/PlayState.cpp.s
.PHONY : src/PlayState.cpp.s

src/TextureManager.o: src/TextureManager.cpp.o
.PHONY : src/TextureManager.o

# target to build an object file
src/TextureManager.cpp.o:
	$(MAKE) -f CMakeFiles/invaders.dir/build.make CMakeFiles/invaders.dir/src/TextureManager.cpp.o
.PHONY : src/TextureManager.cpp.o

src/TextureManager.i: src/TextureManager.cpp.i
.PHONY : src/TextureManager.i

# target to preprocess a source file
src/TextureManager.cpp.i:
	$(MAKE) -f CMakeFiles/invaders.dir/build.make CMakeFiles/invaders.dir/src/TextureManager.cpp.i
.PHONY : src/TextureManager.cpp.i

src/TextureManager.s: src/TextureManager.cpp.s
.PHONY : src/TextureManager.s

# target to generate assembly for a file
src/TextureManager.cpp.s:
	$(MAKE) -f CMakeFiles/invaders.dir/build.make CMakeFiles/invaders.dir/src/TextureManager.cpp.s
.PHONY : src/TextureManager.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/invaders.dir/build.make CMakeFiles/invaders.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/invaders.dir/build.make CMakeFiles/invaders.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/invaders.dir/build.make CMakeFiles/invaders.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/maploader/TMXLoader.o: src/maploader/TMXLoader.cpp.o
.PHONY : src/maploader/TMXLoader.o

# target to build an object file
src/maploader/TMXLoader.cpp.o:
	$(MAKE) -f CMakeFiles/invaders.dir/build.make CMakeFiles/invaders.dir/src/maploader/TMXLoader.cpp.o
.PHONY : src/maploader/TMXLoader.cpp.o

src/maploader/TMXLoader.i: src/maploader/TMXLoader.cpp.i
.PHONY : src/maploader/TMXLoader.i

# target to preprocess a source file
src/maploader/TMXLoader.cpp.i:
	$(MAKE) -f CMakeFiles/invaders.dir/build.make CMakeFiles/invaders.dir/src/maploader/TMXLoader.cpp.i
.PHONY : src/maploader/TMXLoader.cpp.i

src/maploader/TMXLoader.s: src/maploader/TMXLoader.cpp.s
.PHONY : src/maploader/TMXLoader.s

# target to generate assembly for a file
src/maploader/TMXLoader.cpp.s:
	$(MAKE) -f CMakeFiles/invaders.dir/build.make CMakeFiles/invaders.dir/src/maploader/TMXLoader.cpp.s
.PHONY : src/maploader/TMXLoader.cpp.s

src/maploader/base64.o: src/maploader/base64.cpp.o
.PHONY : src/maploader/base64.o

# target to build an object file
src/maploader/base64.cpp.o:
	$(MAKE) -f CMakeFiles/invaders.dir/build.make CMakeFiles/invaders.dir/src/maploader/base64.cpp.o
.PHONY : src/maploader/base64.cpp.o

src/maploader/base64.i: src/maploader/base64.cpp.i
.PHONY : src/maploader/base64.i

# target to preprocess a source file
src/maploader/base64.cpp.i:
	$(MAKE) -f CMakeFiles/invaders.dir/build.make CMakeFiles/invaders.dir/src/maploader/base64.cpp.i
.PHONY : src/maploader/base64.cpp.i

src/maploader/base64.s: src/maploader/base64.cpp.s
.PHONY : src/maploader/base64.s

# target to generate assembly for a file
src/maploader/base64.cpp.s:
	$(MAKE) -f CMakeFiles/invaders.dir/build.make CMakeFiles/invaders.dir/src/maploader/base64.cpp.s
.PHONY : src/maploader/base64.cpp.s

src/tinyxml/tinystr.o: src/tinyxml/tinystr.cpp.o
.PHONY : src/tinyxml/tinystr.o

# target to build an object file
src/tinyxml/tinystr.cpp.o:
	$(MAKE) -f CMakeFiles/invaders.dir/build.make CMakeFiles/invaders.dir/src/tinyxml/tinystr.cpp.o
.PHONY : src/tinyxml/tinystr.cpp.o

src/tinyxml/tinystr.i: src/tinyxml/tinystr.cpp.i
.PHONY : src/tinyxml/tinystr.i

# target to preprocess a source file
src/tinyxml/tinystr.cpp.i:
	$(MAKE) -f CMakeFiles/invaders.dir/build.make CMakeFiles/invaders.dir/src/tinyxml/tinystr.cpp.i
.PHONY : src/tinyxml/tinystr.cpp.i

src/tinyxml/tinystr.s: src/tinyxml/tinystr.cpp.s
.PHONY : src/tinyxml/tinystr.s

# target to generate assembly for a file
src/tinyxml/tinystr.cpp.s:
	$(MAKE) -f CMakeFiles/invaders.dir/build.make CMakeFiles/invaders.dir/src/tinyxml/tinystr.cpp.s
.PHONY : src/tinyxml/tinystr.cpp.s

src/tinyxml/tinyxml.o: src/tinyxml/tinyxml.cpp.o
.PHONY : src/tinyxml/tinyxml.o

# target to build an object file
src/tinyxml/tinyxml.cpp.o:
	$(MAKE) -f CMakeFiles/invaders.dir/build.make CMakeFiles/invaders.dir/src/tinyxml/tinyxml.cpp.o
.PHONY : src/tinyxml/tinyxml.cpp.o

src/tinyxml/tinyxml.i: src/tinyxml/tinyxml.cpp.i
.PHONY : src/tinyxml/tinyxml.i

# target to preprocess a source file
src/tinyxml/tinyxml.cpp.i:
	$(MAKE) -f CMakeFiles/invaders.dir/build.make CMakeFiles/invaders.dir/src/tinyxml/tinyxml.cpp.i
.PHONY : src/tinyxml/tinyxml.cpp.i

src/tinyxml/tinyxml.s: src/tinyxml/tinyxml.cpp.s
.PHONY : src/tinyxml/tinyxml.s

# target to generate assembly for a file
src/tinyxml/tinyxml.cpp.s:
	$(MAKE) -f CMakeFiles/invaders.dir/build.make CMakeFiles/invaders.dir/src/tinyxml/tinyxml.cpp.s
.PHONY : src/tinyxml/tinyxml.cpp.s

src/tinyxml/tinyxmlerror.o: src/tinyxml/tinyxmlerror.cpp.o
.PHONY : src/tinyxml/tinyxmlerror.o

# target to build an object file
src/tinyxml/tinyxmlerror.cpp.o:
	$(MAKE) -f CMakeFiles/invaders.dir/build.make CMakeFiles/invaders.dir/src/tinyxml/tinyxmlerror.cpp.o
.PHONY : src/tinyxml/tinyxmlerror.cpp.o

src/tinyxml/tinyxmlerror.i: src/tinyxml/tinyxmlerror.cpp.i
.PHONY : src/tinyxml/tinyxmlerror.i

# target to preprocess a source file
src/tinyxml/tinyxmlerror.cpp.i:
	$(MAKE) -f CMakeFiles/invaders.dir/build.make CMakeFiles/invaders.dir/src/tinyxml/tinyxmlerror.cpp.i
.PHONY : src/tinyxml/tinyxmlerror.cpp.i

src/tinyxml/tinyxmlerror.s: src/tinyxml/tinyxmlerror.cpp.s
.PHONY : src/tinyxml/tinyxmlerror.s

# target to generate assembly for a file
src/tinyxml/tinyxmlerror.cpp.s:
	$(MAKE) -f CMakeFiles/invaders.dir/build.make CMakeFiles/invaders.dir/src/tinyxml/tinyxmlerror.cpp.s
.PHONY : src/tinyxml/tinyxmlerror.cpp.s

src/tinyxml/tinyxmlparser.o: src/tinyxml/tinyxmlparser.cpp.o
.PHONY : src/tinyxml/tinyxmlparser.o

# target to build an object file
src/tinyxml/tinyxmlparser.cpp.o:
	$(MAKE) -f CMakeFiles/invaders.dir/build.make CMakeFiles/invaders.dir/src/tinyxml/tinyxmlparser.cpp.o
.PHONY : src/tinyxml/tinyxmlparser.cpp.o

src/tinyxml/tinyxmlparser.i: src/tinyxml/tinyxmlparser.cpp.i
.PHONY : src/tinyxml/tinyxmlparser.i

# target to preprocess a source file
src/tinyxml/tinyxmlparser.cpp.i:
	$(MAKE) -f CMakeFiles/invaders.dir/build.make CMakeFiles/invaders.dir/src/tinyxml/tinyxmlparser.cpp.i
.PHONY : src/tinyxml/tinyxmlparser.cpp.i

src/tinyxml/tinyxmlparser.s: src/tinyxml/tinyxmlparser.cpp.s
.PHONY : src/tinyxml/tinyxmlparser.s

# target to generate assembly for a file
src/tinyxml/tinyxmlparser.cpp.s:
	$(MAKE) -f CMakeFiles/invaders.dir/build.make CMakeFiles/invaders.dir/src/tinyxml/tinyxmlparser.cpp.s
.PHONY : src/tinyxml/tinyxmlparser.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... invaders"
	@echo "... rebuild_cache"
	@echo "... src/CFont.o"
	@echo "... src/CFont.i"
	@echo "... src/CFont.s"
	@echo "... src/CGame.o"
	@echo "... src/CGame.i"
	@echo "... src/CGame.s"
	@echo "... src/CImage.o"
	@echo "... src/CImage.i"
	@echo "... src/CImage.s"
	@echo "... src/CMultiImage.o"
	@echo "... src/CMultiImage.i"
	@echo "... src/CMultiImage.s"
	@echo "... src/CSound.o"
	@echo "... src/CSound.i"
	@echo "... src/CSound.s"
	@echo "... src/CSprite.o"
	@echo "... src/CSprite.i"
	@echo "... src/CSprite.s"
	@echo "... src/MenuState.o"
	@echo "... src/MenuState.i"
	@echo "... src/MenuState.s"
	@echo "... src/PauseState.o"
	@echo "... src/PauseState.i"
	@echo "... src/PauseState.s"
	@echo "... src/PlayState.o"
	@echo "... src/PlayState.i"
	@echo "... src/PlayState.s"
	@echo "... src/TextureManager.o"
	@echo "... src/TextureManager.i"
	@echo "... src/TextureManager.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/maploader/TMXLoader.o"
	@echo "... src/maploader/TMXLoader.i"
	@echo "... src/maploader/TMXLoader.s"
	@echo "... src/maploader/base64.o"
	@echo "... src/maploader/base64.i"
	@echo "... src/maploader/base64.s"
	@echo "... src/tinyxml/tinystr.o"
	@echo "... src/tinyxml/tinystr.i"
	@echo "... src/tinyxml/tinystr.s"
	@echo "... src/tinyxml/tinyxml.o"
	@echo "... src/tinyxml/tinyxml.i"
	@echo "... src/tinyxml/tinyxml.s"
	@echo "... src/tinyxml/tinyxmlerror.o"
	@echo "... src/tinyxml/tinyxmlerror.i"
	@echo "... src/tinyxml/tinyxmlerror.s"
	@echo "... src/tinyxml/tinyxmlparser.o"
	@echo "... src/tinyxml/tinyxmlparser.i"
	@echo "... src/tinyxml/tinyxmlparser.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

